### ISSUE TITLE
--ssl-cert-dir doesn't seem to work for nginx (using certbot)

### ISSUE THREAD

**Issue by britannic** [Ubiquiti-App/UNMS#108]
Using standalone TLS/SSL certificates, so installed unms with the following:

bash /tmp/unms_install.sh --ssl-cert-dir /etc/letsencrypt/live/unms.mydomain.org-0001 --ssl-cert fullchain.pem --ssl-cert-key privkey.pem --http-port 8180 --https-port 8181

nginx won't start and listen on port 8181. Log file: [nginx.log](https://github.com/Ubiquiti-App/UNMS/files/1584524/nginx.log)

Tried a full removal (per uninstall guide and then reinstalled with above command line).

See [unms_install.log](https://github.com/Ubiquiti-App/UNMS/files/1584534/unms_install.log).

nginx log had exactly same entries as before, only with different time stamps.

**Comment by radekskrivan** [comment]
Hello @britannic .
I am not sure what may be the cause. I will have to consult this with one of our developers. Will get back to you asap.

**Comment by jaroklima** [comment]
@britannic @radekskrivan The `/etc/letsencrypt/live` directory usually contains symlinks to the actual certificate files under `/etc/letsencrypt/archive`. If that's the case, then `/etc/letsencrypt/live/...` is not a valid value of `--ssl-cert-dir`, because the symlinks stop working when the directory is mounted in a docker container's filesystem. Please try using the `/etc/letsencrypt/archive/...` directory instead. 
(This is apparently missing from our installation manual)

**Comment by britannic** [comment]
That makes sense. Thanks for the update.
