### ISSUE TITLE
UNMS doesn't detect host IP address change of docker host

### ISSUE THREAD

**Issue by benhaines** [Ubiquiti-App/UNMS#123]
I'm running UNMS 0.11.3 in a proxmox Ubuntu 16.04 virtual machine. UNMS was installed using the recommended method and running inside docker. I successfully added a number of devices including an ERX-SFP and ES-24-250W. 

I needed to change the IP of the vm/docker host (via DHCP static reservation), however on reboot UNMS fails to pick up the change of IP. I managed to fix the connections to the Ubnt devices by manually logging in and updating the connection string.

**Comment by radekskrivan** [comment]
@benhaines  Hello Ben. UNMS cannot recognize the IP of its host so you need to go to Settings -> UNMS -> UNMS Hostname/IP and change it. Subsequently, it is necessary to change the connection string on all the devices. Therefore we suggest using FQHN because, as soon as you can control the DNS, you can have a new server with a new IP and just change the DNS record so that the old hostname points to the new address. If you do it this way all device specific UNMS keys inserted into all devices remain valid.

**Comment by benhaines** [comment]
@radekskrivan thanks for the explanation, will close the issue
