### ISSUE TITLE
Country "licensed" is not showing on country list

### ISSUE THREAD

**Issue by moth1995** [Ubiquiti-App/UNMS#164]
Hi! im using this app, is really nice!! i really like it, i got this problem now, if i go into my ap and select "wireless" option for example, change the wireless channel i cant see the "licensed" option on the drop down list.

![imagen](https://user-images.githubusercontent.com/36039932/52523520-f9c66980-2c70-11e9-820f-8dc822d3db7c.png)

There will be any update on this??

**Comment by radekskrivan** [comment]
Hello @moth1995. This is fixed in the 0.13.3-rc.1 version. You can try it out https://community.ubnt.com/t5/UNMS-Alpha/UNMS-version-0-13-3-rc-1-has-been-released/m-p/2664695#M3019
Please note that you need to be a member of the [Early access](https://help.ubnt.com/hc/en-us/articles/204908664-How-To-Sign-Up-for-Early-Access) to open that link.
