### ISSUE TITLE
UNMS without UCRM results in upgrade-loop on startup

### ISSUE THREAD

**Issue by mschmidt291** [Ubiquiti-App/UNMS#170]
We're currently running UNMS 0.13.3 in a Kubernetes Cluster. If we start the 0.14.1 Dockercontainer, it runs "**node ./cli/checkCrmDb.js**" in the initial migrate step and this is resulting in a loop
`Checking CRM database schema version.
relation "crm_db_version_view" does not exist
Retrying in 10s`

Is UCRM now required, or is this a bug? If I set the UCRM_ENABLED=false as an env-variable, it's still trying to check for the UCRM database, even though it's not used.

**Comment by alexdor** [comment]
I'm also facing a similar issue/bug, I've posted about it here https://community.ui.com/questions/UNMS-Upgrading-from-0-13-3-to-0-14-stuck/747612fe-eeb1-4b33-ac2c-7eaa5a3ff76f (I'm using docker-compose instead of Kubernetes)

**Comment by mschmidt291** [comment]
Yes, it actually doesn't matter if you're using kubernetes or docker directly, kubernetes uses dockercontainers, so it's basically really similiar. There should be some check, if you have used UCRM before (for example utilise the UCRM_ENABLED environment variable) to the checkCrmDb.js script, so the CRM-DB check is skipped, once this env variable is set to false

**Comment by radekskrivan** [comment]
Hello  @mschmidt291 @alexdor. Since our final goal is to have UNMS with integrated CRM module and a shared database, the CRM container is necessary to run as well. Without it, UNMS cannot run correctly.
Please note that there were some significant changes in DB between versions 0.13.3 and 0.14.0. It may be best for you to run clean UNMS 0.14.X instance and apply the latest backup there.

**Comment by alexdor** [comment]
@radekskrivan thanks for your response.

Personally I don't think it's a good idea to force people to run a full crm platform just to manage their networking equipment
