### ISSUE TITLE
[Bug] CPU & Memory Spikes - OLT

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#3]
Having the OLT ( 0.2.1-alpha ) connected to the local lan for the last 24 hours i am seeing some weird spikes on the graph with only 2 modules ( UF-OLT-B+ ) plugged in with no onu's connected.

Image Below.

Hourly Graph.
![screen shot 2017-01-01 at 9 11 23 pm](https://cloud.githubusercontent.com/assets/14851974/21584065/95a911ee-d067-11e6-8c0b-f47567082eda.png)

Day Graph.

![screen shot 2017-01-01 at 9 19 16 pm](https://cloud.githubusercontent.com/assets/14851974/21584075/f8fe0b6e-d067-11e6-9153-63e6fb78a437.png)

UI: 0.7.6

**Comment by MartinStrbacka** [comment]
Hello, it might not be related but could you update the OLT to the latest firmware version https://drive.google.com/open?id=0BwHKXNHD5BGmVnJYSXBwS015bVk ? Thanks

**Comment by Dstahl0** [comment]
@MartinStrbacka i upgraded to upgrade-0.2.5- on the OLT. i will keep a watch out in the next few hours and report back.

**Comment by Dstahl0** [comment]
@MartinStrbacka 

Looks like the firmware update worked for the Latency & Outage
![screen shot 2017-01-02 at 3 58 56 pm](https://cloud.githubusercontent.com/assets/14851974/21596109/78b4f196-d104-11e6-8e3f-2222e7634e96.png)

**Comment by Dstahl0** [comment]
CPU & Memory also seems to be more inline to what is expected.

![screen shot 2017-01-02 at 4 07 15 pm](https://cloud.githubusercontent.com/assets/14851974/21596174/9e290fce-d105-11e6-8955-23ccdc166a91.png)

**Comment by Dstahl0** [comment]
Looks like we have a random spike on the graph's, not sure what is causing this.

![screen shot 2017-01-03 at 12 06 36 am](https://cloud.githubusercontent.com/assets/14851974/21600337/99b78fa4-d148-11e6-8470-365e41fd04d7.png)

**Comment by ubnt-michals** [comment]
![image](https://cloud.githubusercontent.com/assets/23234560/21603793/f8d39990-d19f-11e6-908a-14b5bab8f5bb.png)

We've made the line around midnight thicker to signify a new day. Also the thick lines in the monthly graph split the month into different weeks. I hope it makes sense.

**Comment by jflidr** [comment]
There will be rendering fix in version 0.7.8. + there is an OLT HW problem which will fix @MartinStrbacka

**Comment by Dstahl0** [comment]
Thanks for the update @jflidr

**Comment by cdoucet82** [comment]
I am new to the UNMS testing and am seeing the same issue with my ER-lite3.  Since the UNMS firmware and connect sync to UNMS CPU is constantly at 100%.  Can you recommend any solution or info needed to help isolate this as firmware or device issue?

**Comment by jflidr** [comment]
@cdoucet82 thank you for reporting it. I think that this is a different problem which is already fixed in beta FW. Could you please check this [thread](https://community.ubnt.com/t5/UNMS-Ubiquiti-Network-Management/EdgeRouter-Lite-3-CPU-100-w-UNMS-connected/m-p/1982915#M1291) in UNMS community? Thank you.

**Comment by cdoucet82** [comment]
I am unable to view that thread.



Sincerely,

[image: Description: cid:image001.jpg@01CF5268.853652C0]

Cody Doucet| Network Engineer

*BLUETIDE *COMMUNICATIONS



SUPPORT +1 337.205.6720

cdoucet@bluetidecomm.com | bluetidecomm.com <http://www.bluetidecomm.com/>





CONFIDENTIALITY DISCLAIMER: This email message and any attachments are
considered confidential and may be legally privileged and is intended only
for the addressee to view. If you are not the intended recipient of this
email, you are prohibited from disclosing, copying or distributing the
materials in this message, or any action in reliance of the material. If
you have received this email message in error, please contact the sender
immediately and discard this transmission. Thank you.



*From:* Jindrich Flidr [mailto:notifications@github.com]
*Sent:* Friday, July 7, 2017 4:34 PM
*To:* Ubiquiti-App/UNMS
*Cc:* cdoucet82; Mention
*Subject:* Re: [Ubiquiti-App/UNMS] [Bug] CPU & Memory Spikes - OLT (#3)



@cdoucet82 <https://github.com/cdoucet82> thank you for reporting it. I
think that this is a different problem which is already fixed in beta FW.
Could you please check this thread
<https://community.ubnt.com/t5/UNMS-Ubiquiti-Network-Management/EdgeRouter-Lite-3-CPU-100-w-UNMS-connected/m-p/1982915#M1291>
in UNMS community? Thank you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Ubiquiti-App/UNMS/issues/3#issuecomment-313798495>, or mute
the thread

**Comment by jflidr** [comment]
@cdoucet82 If you would like to get access to the thread you have to [register](https://account.ubnt.com/signup?redirect=https%3A%2F%2Fcommunity.ubnt.com%2F) to the community and then you have to enable Beta program in you [account](https://account.ubnt.com/manage/settings/beta).

**Comment by cdoucet82** [comment]
Tricky part is we are using squidguard for content filtering.  I will have
my other engineer look at this issue with me.

**Comment by radekskrivan** [comment]
Closing this older issue. We are now several versions further.
