### ISSUE TITLE
Regarding Firmware 

### ISSUE THREAD

**Issue by amandh** [Ubiquiti-App/UNMS#55]
Dear UNMS Team,

Can you please guide to download firmware of airmax M series v6.0.6, i didn't find it on official site of ubnt
I am firm SUBISU CABLE NET, which is the one of the largest ISP of Nepal, and we are using  huge no of airmax M devices like Rocket M nanostation M and Airgrid M.

Best,
Aman Shrestha

**Comment by jflidr** [comment]
Hi @amandh thank you for your question. You can't download v6.0.6 on official site because it wasn't released yet. There is only an alpha version for community testing before stable release which will be in a few weeks. If you would like to test alpha FW just [write me PM](https://community.ubnt.com/t5/user/viewprofilepage/user-id/377305) and I will post you download link. It's nice to hear from you from Nepal :-)

**Comment by amandh** [comment]
Hello Jindrich,

 As per our previous conversation can you provide me the link so we can
test UNMS.

Thank you,
Aman Shrestha

**Comment by amandh** [comment]
Hi Jindrich,

Can you please share me the Alpha Fw with me.

Thanks Regards,
Aman Shrestha

**Comment by jflidr** [comment]
I suppose that you have account **amandh** in UBNT community. You have disabled PM so I sent it via email.
