### ISSUE TITLE
Firmware upgrade for ER-X

### ISSUE THREAD

**Issue by cbarratt** [Ubiquiti-App/UNMS#75]
I've attempted to upgrade my ER-X twice using the firmware manager in UNMS and both times it has failed to do so. 

It appears to just restart my ER-X but never seems to complete the upgrade.

`upgrade from firmware version 1.9.7-hotfix.2 to firmware version 1.9.7-hotfix.3 has failed because of error (Error: Error: Device upgrade has failed).`

**Comment by jaroklima** [comment]
The device will attempt to download the new firmware from UNMS using the hostname/IP specified in UNMS under Settings/UNMS instead of the address in its UNMS connection string (UNMS key). This often causes issues and we will fix it in UNMS v0.10.0. Related discussion: https://community.ubnt.com/t5/UNMS-Ubiquiti-Network-Management/1-9-7-hotfix1-to-hotfix2-fails/m-p/2038547#M720

If this is the issue, then you can either update the firmware manually until we release a fix, or you can update the hostname/IP in UNMS settings to an address reachable from the device (but this can cause problems for your other devices).

**Comment by cbarratt** [comment]
Thanks for the help pointing me in the right direction. The above scenario completely makes sense :) I see the same thing. My UNMS connection string uses the local IP on my ER-X - but the UNMS FQDN in UNMS is my externally facing DNS name (which can route internally).

I've manually upgraded for now - but figured I'd mention the issue incase it hadn't been reported :)

**Comment by jaroklima** [comment]
And it completely makes sense that you have a private address in one place and a public address in the other. It's something that we've only recently realized and we're making changes in UNMS to reflect it, not only related to firmwares, but throughout the app.
Thank you for reporting the issue.
