### ISSUE TITLE
Change UNMS key NanoBeam 5AC Gen2 failed

### ISSUE THREAD

**Issue by Wiuff** [Ubiquiti-App/UNMS#97]
I have reinstalled my UNMS server, and therefore a new UNMS key is issued. On previous UNMS server I had a mix of 160 NanoStation M5 and NanoBeam 5AC Gen2 distributed on 60 different sites by WAN. All 160 devices connected to the UNMS server without any problems.
When I insert the new UNMS key on NanoStation M5, they immediately connect to the new UNMS server. But when I insert the same new UNMS key into NanoBean 5AC Gen2, on the same site as the NanoStation N5, they do not connect correctly. Instead, I get an error message "Problem with establishing connection from X.X.X.X (WAN IP on site) .Check the UNMS key on the device"
I have tried to disable UNMS function and enable function with new UNMS key, unsuccessfully. A restart of NanoStation 5AC Gen2 has not changed anything. It's not an option to perform a factory default on the devices.
As I see it, it is not possible to write a new UNMS key in NanoBeam 5AC Gen2.
It should be added that I also have 2 NanoBeam 5AC 19, these connect immediately with the new UNMS key.

**Comment by radekskrivan** [comment]
Hello @Wiuff . I believe you can work around that problem by running discovery on the affected devices' IP address. Also here is a short article about [UNMS keys](https://github.com/Ubiquiti-App/UNMS/wiki/UNMS-key-details). I would be most interested to know if the article contains relevant information for you.

**Comment by Wiuff** [comment]
Thanks for the reply. 
Yes I have read the article, and do understand hos it works. :-)
I can not run a discovery, because all devices is on  remote lan via WAN.
/Wiuff

**Comment by radekskrivan** [comment]
@Wiuff  Thank you Wiuff. I was mostly curious about the article since I wrote it and I am not sure if it is clear and informative ;-).
But back to your situation. I suggest that you [check](https://github.com/Ubiquiti-App/UNMS/wiki/Device-log-Troubleshooting#how-to-remove-device-mac-address-from-postgres) the PostgreSQL database for mac addresses of those NanoBeams 5AC Gen2. 
If this database already has mac addresses of those Nano Beams then it is the reason why you are getting the error (AES part of the UNMS key doesn't match). If those devices are not already in PostgreSQL then it is rether strange and we will need to see both [UNMS ](https://github.com/Ubiquiti-App/UNMS/wiki/Discovery-Troubleshooting#where-to-find-unms-logs)and [device logs](https://github.com/Ubiquiti-App/UNMS/wiki/Discovery-Troubleshooting#where-to-find-logs-on-the-device) to find out what is going on.

**Comment by Wiuff** [comment]
I found the mac adresse to one of the NanoBeam 5AC Gen2 in PostgreSQL and deleted it. Now the Nanobeam 5AC Gen2 is in the list of Unauthorized devices. :-)
But there is 86 devices in the PostgreSQL and I do not want to delete one device at a time, is there way to delete them all at once?
Still I wonder why it is only NanoBeam 5AC Gen2, that has this problem, and not NanoStation M5!!

/Wiuff

**Comment by radekskrivan** [comment]
@Wiuff  please be careful with deleting items from that database. There may be some data left in cache and if that happen you may end up in situation, when it will be necessary to reinstall UNMS completely, just to add the cached device. 
If you have this problem with old records in the PostgreSQL database I strongly recommend to either install 0.11.0 Beta2, or wait for a 0.11.0 final release (we hope it will be ready during next week).

**>Still I wonder why it is only NanoBeam 5AC Gen2, that has this problem, and not NanoStation M5!!**
This is not easy to answer since I do not have all the info but basically your new UNMS instance have some old records in its device database. When you try to put new generic UNMS key to a device which already has its unique UNMS key stored in that DB you will get this problem. From this point it seems that the NanoBeam has been in that DB before, but the NanoStation hasn't.

**Comment by Wiuff** [comment]
I will upgrade to 0.11.0 Beta, and then return with an answer whether it works or not.

ALL my devices have been in the DB at the same time. _" On previous UNMS server I had a mix of 160 NanoStation M5 and NanoBeam 5AC Gen2 distributed on 60 different sites by WAN. All 160 devices connected to the UNMS server without any problems."_

/Wiuff

**Comment by Wiuff** [comment]
Upgrade to 0.11.0 has been successfully executed. Here after there are 48 unknown devices. I have done a refresh on them all after which they disappear. NanoBeam 5AC Gen2 can now connect and just be authorized.

/Wiuff

**Comment by radekskrivan** [comment]
It seems correct. Those unknown devices were old records in PostgreSQL database. By refreshing them you safely deleted them from the DB without having to worry about the cache I mentioned earlier.  
I am glad 0.11.0 is working well for you. 

Radek

**Comment by Wiuff** [comment]
@radekskrivan. Thank you for a very good dialogue. It has been a pleasure to solve this challenge with you.

/Wiuff
